name: Check Modified Files in main branch
on:
  push:
    branches:
      - main
jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Modified files
      run: |
        git log --pretty=format:"%h" origin/main..HEAD | while IFS= read -r commit_hash; do
            echo "Commit: $commit_hash"
            git show --stat --color=always $commit_hash
            git show --color=always $commit_hash
        done
          