name: Check Modified Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Modified files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git diff --name-only ${{ github.event.before }}..${{ github.sha }}
            sh filesh.sh
          elif [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            git diff --name-only HEAD^ HEAD
          fi
