name: Check Modified Files
on:
  pull_request:
    branches:
      - main
jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Modified files
      run: |
        git fetch origin main:feature2
        git diff --name-only --diff-filter=d main~ feature2
      
    - name: Run script
      run: bash files_changed.sh
    - name: 2nd sh file
      run: sh filesh.sh
