name: testing yaml linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: YAML linting
        uses: ansible/ansible-lint-action
        with:
          path: |
            **/*.yaml
            **/*.yml
            
