jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: YAML linting
        uses: sdesbure/yamllint-action@v2
        with:
          path: |
            **/*.yaml
            **/*.yml
            
